<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BasaraFoundry.Game.Utage</RootNamespace>
    <AssemblyName>BasaraFoundry.Game.Utage</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
    <ProjectReference Include="..\BasaraFoundry.Domain\BasaraFoundry.Domain.csproj" />
  </ItemGroup>
</Project>
